# Generated by Django 5.2 on 2025-04-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='slug',
        ),
    ]
