# Generated by Django 5.2 on 2025-04-15 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productitem_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='memory',
            field=models.CharField(max_length=7),
        ),
    ]
