# Generated by Django 5.2 on 2025-04-18 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_productitem_memory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='weight',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
