# Generated by Django 5.2 on 2025-04-19 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_attributeoption_attributetype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='option_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
