# Generated by Django 5.2 on 2025-04-19 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_attributeoption_option_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.CharField(max_length=15),
        ),
    ]
