# Generated by Django 5.2 on 2025-04-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
