# Generated by Django 5.2 on 2025-04-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productitem_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
