# Generated by Django 5.2 on 2025-04-23 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_productitem_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='option_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='category',
            table='Categories',
        ),
    ]
