# Generated by Django 5.2 on 2025-04-23 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_attributeoption_option_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='url',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
    ]
