# Generated by Django 5.2 on 2025-04-25 10:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_category_options_remove_category_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributetype',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product_item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productitem')),
            ],
        ),
    ]
