# Generated by Django 5.2 on 2025-05-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_attributetype_id_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='price',
            field=models.FloatField(max_length=15),
        ),
    ]
