# Generated by Django 5.2 on 2025-05-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_alter_productitem_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='sku',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='productitem',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
