# Generated by Django 5.2 on 2025-05-09 16:52

import product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0017_alter_productitem_sku_alter_productitem_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product_item_id',
        ),
        migrations.AddField(
            model_name='productitem',
            name='image',
            field=models.ManyToManyField(related_name='product_items', to='product.image'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=product.models.upload_to),
        ),
    ]
