# Generated by Django 5.2 on 2025-05-10 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributeoption',
            name='category_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='product.category'),
        ),
    ]
