# Generated by Django 5.2 on 2025-05-10 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_attributeoption_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributeoption',
            name='option_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='attributeoption',
            unique_together={('option_name', 'type_id', 'category_id')},
        ),
    ]
